security:
    encoders:
        Wanjee\Shuwee\AdminBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    providers:
        shuwee_provider:
            entity:
                class: ShuweeAdminBundle:User
                property: username

    firewalls:
        admin_area:
            pattern:    ^/admin
            anonymous: ~
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin
            logout:
                path:   /admin/logout
                target: /
            provider: shuwee_provider


    access_control:
            - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_PARAMETER_EDITOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_PARAMETER_ADMIN, ROLE_ALLOWED_TO_SWITCH]