services:
    appbundle.post_admin:
        class: AppBundle\Admin\PostAdmin
        arguments: [@router]
        parent: shuwee_admin.admin_abstract
        tags:
          -  { name: shuwee.admin, alias: post }

    appbundle.twig.app_extension:
        class:     AppBundle\Twig\AppExtension
        arguments: ["@markdown"]
        public:    false
        tags:
          - { name: twig.extension }
