_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

shuwee_admin:
    resource: "@ShuweeAdminBundle/Resources/config/routing.yml"
    prefix: /admin

shuwee_config:
    resource: "@ShuweeConfigBundle/Resources/config/routing.yml"